apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: cloudcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: cart-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:

            - name: USE_DYNAMODB
              value: "false"
            - name: AWS_REGION
              value: "us-east-1"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
